set(_AMENT_PACKAGE_NAME "ugv_sim_tools")
set(ugv_sim_tools_VERSION "0.0.0")
set(ugv_sim_tools_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(ugv_sim_tools_BUILD_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "rosgraph_msgs" "tf2_ros")
set(ugv_sim_tools_BUILDTOOL_DEPENDS "ament_cmake")
set(ugv_sim_tools_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "rosgraph_msgs" "tf2_ros")
set(ugv_sim_tools_BUILDTOOL_EXPORT_DEPENDS )
set(ugv_sim_tools_EXEC_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "sensor_msgs" "rosgraph_msgs" "tf2_ros")
set(ugv_sim_tools_TEST_DEPENDS "ament_cmake_gtest")
set(ugv_sim_tools_GROUP_DEPENDS )
set(ugv_sim_tools_MEMBER_OF_GROUPS )
set(ugv_sim_tools_DEPRECATED "")
set(ugv_sim_tools_EXPORT_TAGS)
list(APPEND ugv_sim_tools_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
