set(_AMENT_PACKAGE_NAME "sim_worlds")
set(sim_worlds_VERSION "0.1.0")
set(sim_worlds_MAINTAINER "Maintainer <maintainer@example.com>")
set(sim_worlds_BUILD_DEPENDS )
set(sim_worlds_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(sim_worlds_BUILD_EXPORT_DEPENDS )
set(sim_worlds_BUILDTOOL_EXPORT_DEPENDS )
set(sim_worlds_EXEC_DEPENDS "ament_index_python" "launch" "launch_ros" "ros_gz_bridge" "ros_gz_sim" "ugv_sim_tools")
set(sim_worlds_TEST_DEPENDS )
set(sim_worlds_GROUP_DEPENDS )
set(sim_worlds_MEMBER_OF_GROUPS )
set(sim_worlds_DEPRECATED "")
set(sim_worlds_EXPORT_TAGS)
list(APPEND sim_worlds_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
