set(_AMENT_PACKAGE_NAME "relative_position_fusion")
set(relative_position_fusion_VERSION "0.0.1")
set(relative_position_fusion_MAINTAINER "OpenAI <dev@openai.local>")
set(relative_position_fusion_BUILD_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "std_msgs" "diagnostic_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "eigen")
set(relative_position_fusion_BUILDTOOL_DEPENDS "ament_cmake")
set(relative_position_fusion_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "std_msgs" "diagnostic_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "eigen")
set(relative_position_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(relative_position_fusion_EXEC_DEPENDS "rclcpp" "geometry_msgs" "nav_msgs" "std_msgs" "diagnostic_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "eigen")
set(relative_position_fusion_TEST_DEPENDS "ament_cmake_gtest")
set(relative_position_fusion_GROUP_DEPENDS )
set(relative_position_fusion_MEMBER_OF_GROUPS )
set(relative_position_fusion_DEPRECATED "")
set(relative_position_fusion_EXPORT_TAGS)
list(APPEND relative_position_fusion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
