set(_AMENT_PACKAGE_NAME "uav_bringup")
set(uav_bringup_VERSION "0.1.0")
set(uav_bringup_MAINTAINER "litianshun <litianshun.cn@gmail.com>")
set(uav_bringup_BUILD_DEPENDS )
set(uav_bringup_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(uav_bringup_BUILD_EXPORT_DEPENDS )
set(uav_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(uav_bringup_EXEC_DEPENDS "launch" "launch_ros" "xacro" "robot_state_publisher" "rviz2" "ament_index_python" "tf2_ros" "uav_description" "uav_bridge" "sim_worlds")
set(uav_bringup_TEST_DEPENDS )
set(uav_bringup_GROUP_DEPENDS )
set(uav_bringup_MEMBER_OF_GROUPS )
set(uav_bringup_DEPRECATED "")
set(uav_bringup_EXPORT_TAGS)
list(APPEND uav_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
